### PR TITLE
Added little test

### PR DESCRIPTION
**Pull request by ZuluPro**
This is a simple expect script:
It ran the server expects some strings and shut it.
Working with demo.

### CODE REVIEW

**Comment by battlemidget** [comment]
Thank you for the test, however, I'd like to see the test in it's own directory and possible makefile targets that run that test making sure system dependencies are installed.  So for anyone wanting to run tests they only need to know `make test` (or the like).

**Comment by ZuluPro** [comment]
For this usage I plan to add `tox.ini`. It'll help us to test accross different versions and just do:
`tox -e $ENV_NAME`.

I'll also add `.travis.yml` using tox

**Comment by ZuluPro** [comment]
Hello @battlemidget 

Don't you think we should merge this PR and I'll add a tox config later ?

**Comment by battlemidget** [comment]
@ZuluPro please provide the remaining tox additions

**Pull request merged**
